#!/bin/bash
#
# 
# 
# 
#
# 
#
# Author : Amine Asli <asli.amine@gmail.com>
#
# Usage :
#       sysconfig-snapshot [--output file] [--compress] [--help] [--version] 
#   

VERSION=0.1
PROGRAM=`basename $0`
IPT=/sbin/iptables
MAX_CONNECTIONS=100
BAN_EXPIRATION=60

ban_ip()
{
   $IPT -I INPUT -s $1 -j DROP && \
   { echo "$IPT -D INPUT -s $1 -j DROP" | at now + $BAN_EXPIRATION minute; }
}

error()
{
   echo "$@" 1>&2
   usage_and_exit 1
}

usage( )
{
   echo "Usage: $PROGRAM ..."
}

usage_and_exit( )
{
   usage
   exit $1
}

version( )
{
   echo "$PROGRAM version $VERSION"
}

while getopts ":hc:e:" opt; do
   case $opt in 
      h  ) 
           usage_and_exit 0
           ;;
      c  )
           MAX_CONNECTIONS="$OPTARG"
           ;;
      e  ) 
           BAN_EXPIRATION="$OPTARG"
           ;;
      l  )
           LOGDIR="$OPTARG"
           ;;
      \? )
           error 
    esac
done


















